# The URL the site will be built for
base_url = "https://mnt.netlify.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

taxonomies = [
    {name = "categories"},
    {name = "tags", paginate_by = 5, rss = true},
    {name = "authors", rss = true},
]

build_search_index = true

[extra]
zulma_themes = ["solar"]

zulma_menu = [
    {url = "$BASE_URL/categories", name = "Categorias"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/authors", name = "Autor"}
]
zulma_brand = {text = "Home"}
zulma_title = "/mnt"
zulma_theme = "solar"
zulma_allow_theme_selection = false